### ISSUE TITLE
Log request additional info

### ISSUE THREAD

**Issue by Globegitter** [balderdashy/sails-hook-dev#2]
Just some more information that might be interesting to log: The paramters of the url so `/api/v1/bla?filter=bla` and possibly also having a timestamp.

I don't have any time for that right now and I still have to look more into https://github.com/mikermcneil/sails-hook-apianalytics, but this is just to track some things I noticed could be useful while working on a project.

**Comment by mikermcneil** [comment]
@Globegitter oh yeah we should totally bring in https://github.com/mikermcneil/sails-hook-apianalytics/blob/master/index.js to here
