### ISSUE TITLE
lodash requires error 

### ISSUE THREAD

**Issue by vbuzzano** [balderdashy/sails-hook-dev#3]
Hello, 

Once sails-hook-dev installed, I got an error lifting sails.

     error: Error: Cannot find module 'lodash/Lang/isObject'
       at Function.Module._resolveFilename (module.js:338:15)
       at Function.Module._load (module.js:280:25)
       at Module.require (module.js:364:17)
       at require (module.js:380:17)
       at Object.<anonymous> (/home/ubuntu/workspace/node_modules/sails-hook-dev/index.js:7:16)
       at Module._compile (module.js:456:26)
       at Object.Module._extensions..js (module.js:474:10)
       at Module.load (/mnt/shared/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
       at Function.Module._load (module.js:312:12)
       at Module.require (module.js:364:17)
       at require (module.js:380:17)
       at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/lib/hooks/moduleloader/index.js:432:26
       at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3740:15
       at forOwn (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:2105:15)
       at Function.reduce (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3737:9)
       at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/lib/hooks/moduleloader/index.js:394:29
       at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/async/lib/async.js:454:17
       at /home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/async/lib/async.js:444:17
       at Array.forEach (native)
       at _each (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/async/lib/async.js:46:24)
       at Object.taskComplete (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/sails/node_modules/async/lib/async.js:443:13)
       at processImmediate [as _immediateCallback] (timers.js:354:15)

In the file index.js   

- var isObject = require('lodash/**Lang**/isObject');    
- var reduce = require('lodash/**Collection**/reduce');    

**Lang** and **Collection** should min to lowercase

- var isObject = require('lodash/**lang**/isObject');    
- var reduce = require('lodash/**collection**/reduce');

**Comment by Globegitter** [comment]
Yep that was my fault. Copied the names from the docs and it is not an issue on Mac. The PR should fix that :)

**Comment by vbuzzano** [comment]
Yeah .. I just see the pull request to fix this. 

Thank you

**Comment by Blackening999** [comment]
Critical Error and blocker. Fix this as fast as possible please.
Also you can refer to this article: https://github.com/joyent/node/issues/6000 in order to investigate more

Thanks

**Comment by Globegitter** [comment]
you can install via `npm i balderdashy/sails-hook-dev --save`

**Comment by Blackening999** [comment]
@Globegitter Thanks!

**Comment by izoj2013** [comment]
@Globegitter - I got the same error with sane-cli on linux mint 17 64bit. After this, the client is up but the backend is dead (understandably). Please, advise.

below is part of the stacktrace
server   | error: Error: Cannot find module 'lodash/Lang/isObject'
server   |     at Function.Module._resolveFilename (module.js:336:15)
server   |     at Function.Module._load (module.js:278:25)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at Object.<anonymous> (/home/theuser/my-app/server/node_modules/sails-hook-dev/index.js:7:16)
server   |     at Module._compile (module.js:460:26)
server   |     at Object.Module._extensions..js (module.js:478:10)
server   |     at Module.load (module.js:355:32)
server   |     at Function.Module._load (module.js:310:12)
server   |     at Module.require (module.js:365:17)
server   |     at require (module.js:384:17)
server   |     at /home/npm-dir/lib/node_modules/sails/lib/hooks/moduleloader/index.js:432:26
server   |     at /home/npm-dir/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3740:15
server   |     at forOwn (/home/npm-dir/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:2105:15)
server   |     at Function.reduce (/home/npm-dir/lib/node_modules/sails/node_modules/lodash/dist/lodash.js:3737:9)
server   |     at /home/npm-dir/lib/node_modules/sails/lib/hooks/moduleloader/index.js:394:29

**Comment by Globegitter** [comment]
@izoj2013 I do apologise about that - same here `npm i balderdashy/sails-hook-dev --save` in the `server` folder will fix the issue.

**Comment by izoj2013** [comment]
@Globegitter Many thanks; its been fixed. 
However, can't install docker-compose based on instructions given at https://docs.docker.com/compose/install/; even if I use 'sudo'. For the time being, will play with some prototypes using disk as db.

iz

**Comment by BransonGitomeh** [comment]
i basically have to do this for every new sane  app, dont we have a permanent fix?

**Comment by Globegitter** [comment]
@BransonGitomeh the upcoming beta of sane will have that fixed from our side. But a new release would be great!

**Comment by anasyb** [comment]
just bumped into this... but google brought this thread up very well :)

**Comment by fijiaaron** [comment]
I edited the file ./server/node_modules/sails-hook-dev/index.js and made Lang and Collection lowercase

var isObject = require('lodash/lang/isObject');
var reduce = require('lodash/collection/reduce');

It would be nice to have a permanent fix in place.

**Comment by shanemgrey** [comment]
It looks like this was updated in master, but there was no version change.  So npm is still installing the locally cached copy with the error still in it unless the user clears npm cache.  This leads to confusion on why uninstall and install don't help.

**Comment by UriKatz** [comment]
bump
