### ISSUE TITLE
Can't find 'lodash/Lang/isObject' directory name is incorrect

### ISSUE THREAD

**Issue by papodaca** [balderdashy/sails-hook-dev#6]
Installing this hook v1.0.0 causes sails to fail to start (Can't find 'lodash/Lang/isObject' directory name is incorrect). Downgrading to 0.2.2 fixes the issue. see: balderdashy/sails#2842

**Comment by papodaca** [comment]
This is seems to have been fixed: balderdashy/sails-hook-dev@7edd086e66e8a428f27859cda02a5b988cc14ad9. Are we going to see a new package release to fix this.

**Comment by TayHobbs** [comment]
+1

**Comment by Blackening999** [comment]
again... the same issue repeated... what a shame :(
https://github.com/balderdashy/sails-hook-dev/issues/3

**Comment by mikermcneil** [comment]
@Blackening999 @TayHobbs @papodaca will republish today.  From here on out, no more private requires! x_X

**Comment by TayHobbs** [comment]
@mikermcneil did you ever cut a new release?

**Comment by IanVS** [comment]
+1

**Comment by hellowin** [comment]
still not published?

**Comment by mrickard** [comment]
While index.js looks correct here on github, installing from npm pulls a 1.0.0 with the improperly capitalized directory names.

**Comment by IanVS** [comment]
@tjwebb, @mikermcneil The version in npm has been broken waiting on a simple publish for several months now.  It would only take a few moments for someone to publish a new version, and a lot of headache would go away for me, as this is used in the SANE project.  Any chance you could help us out and `npm publish`?

**Comment by mattcodez** [comment]
I think I have the same issue, disabling the lodash global causes an error in this hook.

**Comment by prisonier** [comment]
+1

**Comment by mikermcneil** [comment]
would you guys verify this fixes it? https://github.com/balderdashy/sails-hook-dev/pull/9

**Comment by mikermcneil** [comment]
confirmed fixed by https://github.com/balderdashy/sails-hook-dev/pull/9
