### ISSUE TITLE
Module is not registered as a hook

### ISSUE THREAD

**Issue by JamesCropcho** [balderdashy/sails-hook-dev#8]
Hello,

sails-hook-dev doesn't seem to be registered, despite my installation (using `--save`) exactly as specified.

In console, I can't autocomplete to `dev`:

```
sails> sails.hooks.
sails.hooks.__defineGetter__      sails.hooks.__defineSetter__      sails.hooks.__lookupGetter__      sails.hooks.__lookupSetter__
sails.hooks.constructor           sails.hooks.hasOwnProperty        sails.hooks.isPrototypeOf         sails.hooks.propertyIsEnumerable
sails.hooks.toLocaleString        sails.hooks.toString              sails.hooks.valueOf               

sails.hooks.blueprints            sails.hooks.controllers           sails.hooks.cors                  sails.hooks.csrf
sails.hooks.http                  sails.hooks.i18n                  sails.hooks.logger                sails.hooks.moduleloader
sails.hooks.orm                   sails.hooks.policies              sails.hooks.pubsub                sails.hooks.request
sails.hooks.responses             sails.hooks.services              sails.hooks.session               sails.hooks.sockets
sails.hooks.userconfig            sails.hooks.userhooks             sails.hooks.views                 

sails> 
```

and when accessing `http://localhost:1337/dev` via browser I get:

```
{
id: "error",
title: "Resource not found",
errors: [
"Resource not found"
],
instance: "/dev"
}
```

Any ideas? Help would be much appreciated!

Thanks,
James

**Comment by mikermcneil** [comment]
@JamesCropcho I haven't been able to replicate this -- and I haven't seen that error message before (is that from a custom `notFound` response?)

Would you give this another go using the latest version of this package, and the latest sails?  Thanks

**Comment by JamesCropcho** [comment]
Hello Mike ( @mikermcneil ),

Great of you to get back me, and to revisit this problem. A hearty thanks from the Sails.js community.

it's actually been couple years since I worked on this codebase. I no longer have access to it, so I am not able to give it another go. However, I am forwarding your message/request to the maintainers of the codebase in case they want weigh in.


Best,
James

**Comment by mikermcneil** [comment]
@JamesCropcho thanks!
